spring:
  config:
    activate:
      on-profile: pre

endpoint:
  tinubu:
    url: https://rmc.tinubu.com/pegase/servlet/WsServlet
    user: 'cescews'
    pass: 'tinubu'
    service: "submitRequest"
