<<<<<<< HEAD
spring:
  config:
    activate:
      on-profile: pre

endpoint:
  tinubu:
    url: https://rmc.tinubu.com/pegase/servlet/WsServlet
    user: 'cescews'
    pass: 'tinubu'
    service: "submitRequest"
=======
spring:
  config:
    activate:
      on-profile: pre

endpoint:
  tinubu:
    url: https://rmc.tinubu.com/pegase/servlet/WsServlet
    user: 'cescews'
    pass: 'tinubu'
    service: "submitRequest"
>>>>>>> 432969fafb2f9ebe279d1d1efc159a4db9fa7ce0
